version: '3.1'

services:

  bitblog:
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - 74:80

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  

